name: Continuous Integration

on:
  push:
    branches: [prettier-workflow-test]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --parser markdown \
            --prose-wrap always \
            --print-width 80 \
            --write source/*.md
          only_changed: True
          same_commit: True
